### ISSUE TITLE
"GET /fees" http-request

### ISSUE THREAD

**Issue by avmarko** [tpodlaski/copra#8]
Hi. 
Are there any plans to add support for the "GET /fees" http-request in the near future? 

"This request will return your current maker & taker fee rates, as well as your 30-day trailing volume. Quoted rates are subject to change. More information on fees can found on our support page."

Thanks in advance

**Comment by tpodlaski** [comment]
Hello,

Thanks for bringing this my attention. I just added a rest.Client.fees method to version 1.2.9. The unit test passes but the functional test fails because apparently the sandbox server hasn't had it's API upgraded yet. I did try it against the live server and it worked fine. I will be uploading this new version to PyPi shortly. Let me know if you run into any issue with it.

Thanks again.

Thanks!

**Comment by avmarko** [comment]
That was really fast! Many thanks!
